//Generated by the Argon Build System


#ifndef __Epic_Ecliptic__EpicEclipticBase__
#define __Epic_Ecliptic__EpicEclipticBase__

#include <ArgonEngine/MeshFormat.h>
#include <ArgonEngine/Node.h>
#include <ArgonEngine/Hardware.h>
#include <iostream>
#include <ArgonEngine/ParticleSystem.h>

struct ArgonAppBase : public Argon::Node {

    std::shared_ptr<Argon::Node>light;
    Argon::MeshFormat model;
    float total_time=0;
    Argon::Input input;
    ArgonAppBase();


    std::shared_ptr<Node> animate(float time);


};
#endif /* defined(__Epic_Ecliptic__EpicEclipticBase__) */
