//Generated by the Argon Build System

//
//  AdController.cpp
//  ArgonEngine
//
//  Created by Skyler Saleh on 9/3/12.
//  Copyright (c) 2012 Argon Software. All rights reserved.
//

#include "AdController.h"
namespace Argon {
	int AdController::banner_users=0;
    bool AdController::show_pop_up_=false;
	bool AdController::show_cross_app_promotion_=false;
	StringIntern AdController::pop_up_id="";
	void AdController::hide_banner(){
		mutex().lock();
		if(banner_visible) banner_users--;
		banner_visible = false;
		mutex().unlock();
	}
	void AdController::show_banner(){
		mutex().lock();
		if(!banner_visible) banner_users++;
		banner_visible = true;
		mutex().unlock();
	}
    void AdController::show_pop_up(const StringIntern& ident){
        mutex().lock();
        pop_up_id=ident;
        show_pop_up_=true;
        mutex().unlock();
    }

    bool AdController::should_show_pop_up(){
        mutex().lock();
        bool b = show_pop_up_;
        show_pop_up_=false;
        mutex().unlock();
        return b;
    }
    bool AdController::should_show_cross_app_promotion(){
        mutex().lock();
        bool b = show_cross_app_promotion_;
        show_cross_app_promotion_=false;
        mutex().unlock();
        return b;
    }
    void AdController::show_cross_app_promotion(){
        mutex().lock();
        show_cross_app_promotion_=true;
        mutex().unlock();
    }
};