//Generated by the Argon Build System

//
//  ARUserInterface.cpp
//  Neon Rush
//
//  Created by Skyler Saleh on 6/22/12.
//  Copyright (c) 2012 Argon Software. All rights reserved.
//

#include "UserInterface.h"
namespace Argon{
   
}