//Generated by the Argon Build System

//
//  ARUserMusic.cpp
//  Neon Rush
//
//  Created by Skyler Saleh on 7/10/12.
//  Copyright (c) 2012 Argon Software. All rights reserved.
//

#include "UserMusic.h"
#include <iostream>
Argon::UserMusicState Argon::UserMusic::state;
bool         Argon::UserMusic::supported_;
bool Argon::UserMusic::set_state(Argon::UserMusicState s){
	if(triggered_state==s) {
		if(state!=s) {
			triggered_state = kMusicStateNone;
			return true;
		}
	}else{
		triggered_state = s;
		state = s;
	}
	return false;
}