//Generated by Argon Build System
// Platform Detection
#ifdef _WIN64
    #define PLATFORM_WINDOWS 1
    #define PLATFORM_WINDOWS64 1
#elif _WIN32
   #define PLATFORM_WINDOWS 1
#elif __APPLE__
    #include "TargetConditionals.h"
    #define PLATFORM_APPLE 1
    #define PLATFORM_UNIX 1
    #define PLATFORM_POSIX 1
    #if TARGET_OS_IPHONE
        #define PLATFORM_IOS 1
    #elif TARGET_IPHONE_SIMULATOR
        #define PLATFORM_IOS_SIMULATOR 1
        #define PLATFORM_IOS 1
    #elif TARGET_OS_MAC
        #define PLATFORM_MAC 1
    #else
        #warning Unknown Apple Platform
    #endif
#elif __linux
    #define PLATFORM_LINUX 1
    #define PLATFORM_UNIX  1
    #define PLATFORM_POSIX 1
#elif __unix // all unices not caught above
    #define PLATFORM_UNIX  1
#elif __posix
    #define PLATFORM_POSIX 1
#endif
#ifdef __GNUC__
#define VARIABLE_IS_NOT_USED __attribute__ ((unused))
#else
#define VARIABLE_IS_NOT_USED
#endif
#define USE_OPENGL 1
#define EIGEN_MPL2_ONLY
#define USE_SDL 1
#define SDL_RENDER_DISABLED 1
#define GRAPHICS_DEBUG_LEVEL 0
#define HAVE_LIBC
#ifdef __ANDROID__
    #define PLATFORM_ANDROID

#endif
#ifdef PLATFORM_ANDROID
    #define USE_OPENGLES 1
#endif
// #define USE_OPENCL
// #define USE_DX11

// Opus Config
#define OPUS_BUILD 1
#define FLOAT_APPROX 1
#define HAVE_MEMORY_H 1
#define STDC_HEADERS 1
#define HAVE_LRINTF 1



#ifdef PLATFORM_POSIX
    #define USE_PTHREADS 1
    #define VAR_ARRAYS 1
#endif
#ifndef PLATFORM_POSIX
#endif
#ifdef PLATFORM_WINDOWS
    #define __MINGW32__ 1
    #define USE_ALLOCA 1
#ifndef NOMINMAX
    #define NOMINMAX
#endif
    #define WIN32_LEAN_MEAN
    #define GLEW_STATIC
#endif
#ifdef PLATFORM_APPLE
    #define __MACOSX_CORE__ 1
    #define USE_CURL

#endif
#ifdef PLATFORM_LINUX

#endif
#ifndef USE_OPENGLES
    #define HAVE_OPENGL 1
    #define GLEW_NO_GLU
    #define USE_GLEW 1


#endif
